package UI;
import Model.AccountInformation;
import Model.Address;
import Model.Demoraphic;
import Model.DriverLicenseInformation;
import Model.MedicalRecord;
import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


/**
 *
 * @author SachinSurya
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    Demoraphic demographic;
    Address address;
    AccountInformation accInfo;
    DriverLicenseInformation license;
    MedicalRecord medical;
    public MainFrame() {
        initComponents();
        addEventListeners();
        demographic = new Demoraphic();
        address = new Address();
        accInfo = new AccountInformation();
        license = new DriverLicenseInformation();
        medical = new MedicalRecord();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Header = new javax.swing.JLabel();
        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        createBtn = new javax.swing.JButton();
        viewBtn = new javax.swing.JButton();
        tabPane = new javax.swing.JTabbedPane();
        demographicView = new javax.swing.JPanel();
        addressView = new javax.swing.JPanel();
        savingsView = new javax.swing.JPanel();
        licenseView = new javax.swing.JPanel();
        checkingAccountView = new javax.swing.JPanel();
        medicalView = new javax.swing.JPanel();
        finalView = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Header.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Header.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Header.setText("REPORT");

        createBtn.setText("Create");

        viewBtn.setText("View");
        viewBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(createBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                    .addComponent(viewBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(201, 201, 201)
                .addComponent(createBtn)
                .addGap(18, 18, 18)
                .addComponent(viewBtn)
                .addContainerGap(275, Short.MAX_VALUE))
        );

        jSplitPane1.setLeftComponent(jPanel1);

        javax.swing.GroupLayout demographicViewLayout = new javax.swing.GroupLayout(demographicView);
        demographicView.setLayout(demographicViewLayout);
        demographicViewLayout.setHorizontalGroup(
            demographicViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 886, Short.MAX_VALUE)
        );
        demographicViewLayout.setVerticalGroup(
            demographicViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 512, Short.MAX_VALUE)
        );

        tabPane.addTab("Demographic Details", demographicView);

        javax.swing.GroupLayout addressViewLayout = new javax.swing.GroupLayout(addressView);
        addressView.setLayout(addressViewLayout);
        addressViewLayout.setHorizontalGroup(
            addressViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 886, Short.MAX_VALUE)
        );
        addressViewLayout.setVerticalGroup(
            addressViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 512, Short.MAX_VALUE)
        );

        tabPane.addTab("Address Details", addressView);

        javax.swing.GroupLayout savingsViewLayout = new javax.swing.GroupLayout(savingsView);
        savingsView.setLayout(savingsViewLayout);
        savingsViewLayout.setHorizontalGroup(
            savingsViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 886, Short.MAX_VALUE)
        );
        savingsViewLayout.setVerticalGroup(
            savingsViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 512, Short.MAX_VALUE)
        );

        tabPane.addTab("Savings Account Information", savingsView);

        javax.swing.GroupLayout licenseViewLayout = new javax.swing.GroupLayout(licenseView);
        licenseView.setLayout(licenseViewLayout);
        licenseViewLayout.setHorizontalGroup(
            licenseViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 886, Short.MAX_VALUE)
        );
        licenseViewLayout.setVerticalGroup(
            licenseViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 512, Short.MAX_VALUE)
        );

        tabPane.addTab("Drivers License Information", licenseView);

        javax.swing.GroupLayout checkingAccountViewLayout = new javax.swing.GroupLayout(checkingAccountView);
        checkingAccountView.setLayout(checkingAccountViewLayout);
        checkingAccountViewLayout.setHorizontalGroup(
            checkingAccountViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 886, Short.MAX_VALUE)
        );
        checkingAccountViewLayout.setVerticalGroup(
            checkingAccountViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 512, Short.MAX_VALUE)
        );

        tabPane.addTab("Checking Account Information", checkingAccountView);

        javax.swing.GroupLayout medicalViewLayout = new javax.swing.GroupLayout(medicalView);
        medicalView.setLayout(medicalViewLayout);
        medicalViewLayout.setHorizontalGroup(
            medicalViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 886, Short.MAX_VALUE)
        );
        medicalViewLayout.setVerticalGroup(
            medicalViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 512, Short.MAX_VALUE)
        );

        tabPane.addTab("Medical Information", medicalView);

        javax.swing.GroupLayout finalViewLayout = new javax.swing.GroupLayout(finalView);
        finalView.setLayout(finalViewLayout);
        finalViewLayout.setHorizontalGroup(
            finalViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 886, Short.MAX_VALUE)
        );
        finalViewLayout.setVerticalGroup(
            finalViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 512, Short.MAX_VALUE)
        );

        tabPane.addTab("Final Report", finalView);

        jSplitPane1.setRightComponent(tabPane);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(465, 465, 465)
                .addComponent(Header)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jSplitPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(Header)
                .addGap(18, 18, 18)
                .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 542, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void viewBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_viewBtnActionPerformed

    private void addEventListeners(){
        tabPane.addChangeListener(new ChangeListener() {
            @Override
            public void stateChanged(ChangeEvent e) {
                System.out.println(tabPane.getSelectedIndex()); //To change body of generated methods, choose Tools | Templates.
            }
        });
    }
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Header;
    private javax.swing.JPanel addressView;
    private javax.swing.JPanel checkingAccountView;
    private javax.swing.JButton createBtn;
    private javax.swing.JPanel demographicView;
    private javax.swing.JPanel finalView;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JPanel licenseView;
    private javax.swing.JPanel medicalView;
    private javax.swing.JPanel savingsView;
    private javax.swing.JTabbedPane tabPane;
    private javax.swing.JButton viewBtn;
    // End of variables declaration//GEN-END:variables
}
